[package]
name = "cargo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
proc-macro2 = "1.0.87"
quote = "1.0.37"
regex = "1.11.0"
syn = { version = "2.0.79", features = ["extra-traits", "full"] }
